import React,{FormEvent,useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';
import'./ai.css';

const API='';
type User={id:number;email:string;full_name:string;role:string;is_active:boolean};
type Req={id:number;request_no:string;requester_id:number;requester_email?:string;requester_name?:string;proposed_name:string;supplier_material_code?:string;description?:string;unit?:string;material_group?:string;category_id?:number;category_name?:string;brand_id?:number;brand_name?:string;status:string;masterdata_note?:string;accounting_note?:string;result_material_code?:string;created_at:string;updated_at:string};
type Mat={id:number;material_code:string;material_name:string;description?:string;unit?:string;material_group?:string;category_name?:string;brand_name?:string};
type RefItem={id:number;code:string;name:string};
type Form={proposed_name:string;supplier_material_code:string;description:string;unit:string;material_group:string;category_id:string;brand_id:string};
type AiSuggestion={suggested_name:string;category_id?:number;category_name?:string;brand_id?:number;brand_name?:string;explanation:string;warnings:string[];similar_items:{material_code:string;material_name:string;score:number}[]};
type SyncStatus={source_name:string;last_synced_at?:string;row_count:number;status:string;message?:string};
const empty:Form={proposed_name:'',supplier_material_code:'',description:'',unit:'',material_group:'',category_id:'',brand_id:''};
const labels:Record<string,string>={PENDING_MASTERDATA:'Chờ Masterdata duyệt & cấp mã',PENDING_ACCOUNTING:'Chờ Kế toán phê duyệt cuối',PENDING_CODE_ASSIGNMENT:'Chờ Masterdata cấp mã',RETURNED_TO_REQUESTER:'Đã trả lại người lập',COMPLETED:'Hoàn tất',REJECTED:'Từ chối'};
const fmt=(v?:string)=>v?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'-';

function App(){
 const[token,setToken]=useState(localStorage.getItem('token')||'');const[user,setUser]=useState<User|null>(null);const[err,setErr]=useState('');const[tab,setTab]=useState<'portal'|'users'>('portal');
 const[reqs,setReqs]=useState<Req[]>([]);const[status,setStatus]=useState('');const[form,setForm]=useState<Form>(empty);const[showForm,setShowForm]=useState(false);const[edit,setEdit]=useState<Req|null>(null);const[editForm,setEditForm]=useState<Form>(empty);
 const[q,setQ]=useState('');const[mats,setMats]=useState<Mat[]>([]);const[searched,setSearched]=useState(false);const[searchTotal,setSearchTotal]=useState(0);const[users,setUsers]=useState<User[]>([]);const[newUser,setNewUser]=useState({email:'',full_name:'',role:'USER',password:'12345678'});const[sync,setSync]=useState<SyncStatus|null>(null);const[categories,setCategories]=useState<RefItem[]>([]);const[brands,setBrands]=useState<RefItem[]>([]);const[ai,setAi]=useState<AiSuggestion|null>(null);const[aiLoading,setAiLoading]=useState(false);
 const headers=(json=true)=>({...(json?{'Content-Type':'application/json'}:{}),Authorization:`Bearer ${token}`});
 async function api(path:string,opt:any={}){const r=await fetch(API+path,{...opt,headers:{...headers(opt.body!==undefined),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)logout();throw new Error(d.detail||'Có lỗi xảy ra');}return d}
 function logout(){localStorage.removeItem('token');setToken('');setUser(null)}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setErr('');const fd=new FormData(e.currentTarget);try{const r=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Đăng nhập thất bại');localStorage.setItem('token',d.access_token);setToken(d.access_token);setUser(d.user)}catch(x){setErr(x instanceof Error?x.message:'Đăng nhập thất bại')}}
 async function loadMe(){if(!token)return;try{setUser(await api('/api/v1/auth/me'))}catch{}}
 async function loadReqs(s=status){if(!user)return;try{const d=await api('/api/v1/requests'+(s?`?status=${encodeURIComponent(s)}`:''));setReqs(d.items||[])}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 async function loadUsers(){if(user?.role!=='ADMIN')return;try{const d=await api('/api/v1/users');setUsers(d.items||[])}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 async function loadSync(){try{setSync(await api('/api/v1/sync-status'))}catch{}}
 async function loadReferences(){try{const[c,b]=await Promise.all([api('/api/v1/categories'),api('/api/v1/brands')]);setCategories(c.items||[]);setBrands(b.items||[])}catch{}}
 useEffect(()=>{if(token&&!user)loadMe()},[token]);useEffect(()=>{if(user){loadReqs('');loadSync();loadReferences();if(user.role==='ADMIN')loadUsers()}},[user]);
 async function search(e:FormEvent){e.preventDefault();try{const d=await api(`/api/v1/materials/search?q=${encodeURIComponent(q)}&limit=20`);setMats(d.items||[]);setSearchTotal(d.total||0);setSearched(true)}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 async function createReq(e:FormEvent){e.preventDefault();try{await api('/api/v1/requests',{method:'POST',body:JSON.stringify({...form,supplier_material_code:form.supplier_material_code||null,category_id:form.category_id?Number(form.category_id):null,brand_id:form.brand_id?Number(form.brand_id):null})});setForm(empty);setAi(null);setShowForm(false);await loadReqs('')}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 async function act(r:Req,action:string){let note:string|null=null,material_code:string|null=null;if(action==='RETURN'){note=prompt('Lý do trả lại người lập:');if(note===null||!note.trim())return}else if(action==='APPROVE'&&r.status==='PENDING_MASTERDATA'){material_code=prompt('Nhập mã hàng mới được cấp:');if(material_code===null||!material_code.trim())return;note=prompt('Ghi chú Masterdata (có thể để trống):');if(note===null)return}else if(action==='APPROVE'){note=prompt('Ghi chú Kế toán (có thể để trống):');if(note===null)return}else if(action==='ASSIGN_CODE'){material_code=prompt('Nhập mã hàng mới được cấp:');if(material_code===null||!material_code.trim())return;note=prompt('Ghi chú Masterdata (có thể để trống):');if(note===null)return}else if(action==='RESUBMIT'&&!confirm('Gửi duyệt lại yêu cầu này?'))return;try{await api(`/api/v1/requests/${r.id}/transition`,{method:'POST',body:JSON.stringify({action,note,material_code})});await loadReqs(status)}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 function openEdit(r:Req){setEdit(r);setEditForm({proposed_name:r.proposed_name,supplier_material_code:r.supplier_material_code||'',description:r.description||'',unit:r.unit||'',material_group:r.material_group||'',category_id:String(r.category_id||''),brand_id:String(r.brand_id||'')})}
 async function suggestName(){if(form.proposed_name.trim().length<2)return;setAiLoading(true);setAi(null);try{const x=await api('/api/v1/ai/suggest-name',{method:'POST',body:JSON.stringify({proposed_name:form.proposed_name,description:form.description||null})});setAi(x)}catch(x){setErr(x instanceof Error?x.message:'AI không phản hồi')}finally{setAiLoading(false)}}
 async function saveEdit(e:FormEvent,resubmit:boolean){e.preventDefault();if(!edit)return;try{const u=await api(`/api/v1/requests/${edit.id}`,{method:'PATCH',body:JSON.stringify({...editForm,supplier_material_code:editForm.supplier_material_code||null,category_id:editForm.category_id?Number(editForm.category_id):null,brand_id:editForm.brand_id?Number(editForm.brand_id):null})});setEdit(null);if(resubmit)await act(u,'RESUBMIT');else await loadReqs(status)}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 function actions(r:Req){if(user?.role==='MASTERDATA'&&r.status==='PENDING_MASTERDATA')return <><button className="small approve" onClick={()=>act(r,'APPROVE')}>Duyệt & cấp mã</button><button className="small reject" onClick={()=>act(r,'RETURN')}>Trả lại</button></>;if(user?.role==='ACCOUNTING'&&r.status==='PENDING_ACCOUNTING')return <><button className="small approve" onClick={()=>act(r,'APPROVE')}>Phê duyệt cuối</button><button className="small reject" onClick={()=>act(r,'RETURN')}>Trả lại</button></>;if(user?.role==='MASTERDATA'&&r.status==='PENDING_CODE_ASSIGNMENT')return <><button className="small approve" onClick={()=>act(r,'ASSIGN_CODE')}>Cấp mã & chuyển Kế toán</button><button className="small reject" onClick={()=>act(r,'RETURN')}>Trả lại</button></>;if((user?.role==='USER'||user?.role==='ADMIN')&&r.status==='RETURNED_TO_REQUESTER')return <><button className="small approve" onClick={()=>openEdit(r)}>Mở & sửa</button><button className="small" onClick={()=>act(r,'RESUBMIT')}>Gửi lại</button></>;return null}
 async function addUser(e:FormEvent){e.preventDefault();try{await api('/api/v1/users',{method:'POST',body:JSON.stringify({...newUser,is_active:true})});setNewUser({email:'',full_name:'',role:'USER',password:'12345678'});await loadUsers()}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 async function updateUser(u:User,patch:any){try{await api(`/api/v1/users/${u.id}`,{method:'PATCH',body:JSON.stringify(patch)});await loadUsers()}catch(x){setErr(x instanceof Error?x.message:'Lỗi')}}
 if(!token||!user)return <div className="login-page"><form className="login-card" onSubmit={login}><img src="/logo.svg"/><h1>Material Masterdata Portal</h1><p>Đăng nhập hệ thống quản lý yêu cầu đặt mã</p>{err&&<div className="notice error">{err}</div>}<label>Email<input name="email" type="email" defaultValue="user@example.com" required/></label><label>Mật khẩu<input name="password" type="password" defaultValue="12345678" required/></label><button className="primary">Đăng nhập</button></form></div>;
 return <main className="page"><header className="app-header"><div className="brand"><img src="/logo.svg"/><div><b>Material Masterdata Portal</b><span>V1.5.2 · DOVITEC</span></div></div><nav><button className={tab==='portal'?'active':''} onClick={()=>setTab('portal')}>Yêu cầu vật tư</button>{user.role==='ADMIN'&&<button className={tab==='users'?'active':''} onClick={()=>{setTab('users');loadUsers()}}>Người dùng & phân quyền</button>}</nav><div className="account"><div><b>{user.full_name}</b><span>{user.role}</span></div><button onClick={logout}>Đăng xuất</button></div></header>{err&&<div className="global-error notice error">{err}</div>}
 {tab==='users'&&user.role==='ADMIN'?<section className="admin-page"><div className="section-title"><div><span className="eyebrow">QUẢN TRỊ</span><h2>Người dùng & phân quyền</h2></div></div><form className="user-create" onSubmit={addUser}><input placeholder="Họ tên" value={newUser.full_name} onChange={e=>setNewUser({...newUser,full_name:e.target.value})} required/><input type="email" placeholder="Email" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})} required/><select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}><option>USER</option><option>MASTERDATA</option><option>ACCOUNTING</option><option>ADMIN</option></select><input type="password" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})} minLength={8}/><button className="primary">+ Thêm người dùng</button></form><div className="table-wrap"><table><thead><tr><th>Họ tên</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name}</b></td><td>{u.email}</td><td><select value={u.role} onChange={e=>updateUser(u,{role:e.target.value})}><option>USER</option><option>MASTERDATA</option><option>ACCOUNTING</option><option>ADMIN</option></select></td><td>{u.is_active?'Hoạt động':'Đã khóa'}</td><td><button className="small" onClick={()=>updateUser(u,{is_active:!u.is_active})}>{u.is_active?'Khóa':'Mở khóa'}</button><button className="small" onClick={()=>{const p=prompt('Mật khẩu mới (tối thiểu 8 ký tự):');if(p&&p.length>=8)updateUser(u,{password:p})}}>Đặt lại mật khẩu</button></td></tr>)}</tbody></table></div></section>:<>
 <section className="hero compact"><div className="hero-copy"><span className="badge">DOVITEC · Material Masterdata</span><h1>Tra cứu & yêu cầu đặt mã vật tư</h1><p>{sync?.last_synced_at?<>Đồng bộ dữ liệu Bravo mới nhất lúc: <b>{fmt(sync.last_synced_at)}</b> · {sync.row_count.toLocaleString('vi-VN')} vật tư</>:<>Chưa có thông tin đồng bộ Bravo.</>}</p></div><form className="search" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nhập mã, tên hoặc mô tả vật tư..."/><button>Tìm kiếm</button></form>{(user.role==='USER'||user.role==='ADMIN')&&<button className="request" onClick={()=>setShowForm(v=>!v)}>{showForm?'Đóng form':'+ Tạo yêu cầu'}</button>}</section>
 {showForm&&<section className="request-panel"><h2>Tạo yêu cầu đặt mã</h2><form className="request-form" onSubmit={createReq}><label>Tên vật tư *<input required value={form.proposed_name} onChange={e=>setForm({...form,proposed_name:e.target.value})}/></label><button type="button" className="secondary" disabled={aiLoading||form.proposed_name.trim().length<2} onClick={suggestName}>{aiLoading?'AI đang phân tích...':'✦ AI đề xuất tên chuẩn'}</button>{ai&&<div className="notice ai-box"><b>{ai.suggested_name}</b><p>Chủng loại: {ai.category_name||'Chưa xác định'} · Nhãn hiệu: {ai.brand_name||'Chưa xác định'}</p><p>{ai.explanation}</p>{ai.warnings.map((w,i)=><small key={i}>⚠ {w}</small>)}<button type="button" className="small" onClick={()=>setForm({...form,proposed_name:ai.suggested_name,category_id:String(ai.category_id||''),brand_id:String(ai.brand_id||'')})}>Áp dụng tên này</button></div>}<label>Mã vật tư Nhà cung cấp<input value={form.supplier_material_code} onChange={e=>setForm({...form,supplier_material_code:e.target.value})} placeholder="Nhập mã của nhà cung cấp nếu có"/></label><label>Mô tả / quy cách<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-row"><label>Đơn vị tính<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Nhóm vật tư<input value={form.material_group} onChange={e=>setForm({...form,material_group:e.target.value})}/></label></div><div className="form-row"><label>Chủng loại<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">-- Chọn --</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Nhãn hiệu<select value={form.brand_id} onChange={e=>setForm({...form,brand_id:e.target.value})}><option value="">-- Chọn --</option>{brands.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><button className="primary">Gửi yêu cầu</button></form></section>}
 {searched&&<section className="results"><h2>Kết quả tra cứu, chỉ hiển thị {mats.length}/{searchTotal}</h2>{mats.length===0?<div className="empty">Không tìm thấy vật tư phù hợp.</div>:<div className="table-wrap"><table><thead><tr><th>Mã</th><th>Tên vật tư</th><th>Chủng loại</th><th>Nhãn hiệu</th><th>Mô tả</th><th>ĐVT</th><th>Nhóm</th></tr></thead><tbody>{mats.map(m=><tr key={m.id}><td><b>{m.material_code}</b></td><td>{m.material_name}</td><td>{m.category_name||'-'}</td><td>{m.brand_name||'-'}</td><td>{m.description||'-'}</td><td>{m.unit||'-'}</td><td>{m.material_group||'-'}</td></tr>)}</tbody></table></div>}</section>}
 <section className="requests-section"><div className="section-title"><div><span className="eyebrow">{user.role==='USER'?'YÊU CẦU CỦA TÔI':'HÀNG CHỜ XỬ LÝ'}</span><h2>Danh sách yêu cầu đặt mã</h2></div><button className="refresh" onClick={()=>loadReqs(status)}>↻ Làm mới</button></div><div className="filters">{[['','Tất cả'],['PENDING_MASTERDATA','Chờ Masterdata'],['PENDING_ACCOUNTING','Chờ Kế toán'],['PENDING_CODE_ASSIGNMENT','Dữ liệu cũ chờ cấp mã'],['RETURNED_TO_REQUESTER','Trả người lập'],['COMPLETED','Hoàn tất']].map(([v,l])=><button className={status===v?'active':''} onClick={()=>{setStatus(v);loadReqs(v)}} key={v||'all'}>{l}</button>)}</div><div className="request-list">{reqs.map(r=><article className="request-card full" key={r.id}><div className="request-card-main"><div className="request-no">{r.request_no}</div><h3>{r.proposed_name}</h3><div className="request-detail-grid"><div><span>Mã vật tư Nhà cung cấp</span><b>{r.supplier_material_code||'-'}</b></div><div><span>Mô tả / quy cách</span><b>{r.description||'-'}</b></div><div><span>Đơn vị tính</span><b>{r.unit||'-'}</b></div><div><span>Nhóm vật tư</span><b>{r.material_group||'-'}</b></div><div><span>Người tạo</span><b>{r.requester_name||r.requester_email||'-'}</b></div><div><span>Thời gian tạo</span><b>{fmt(r.created_at)}</b></div><div><span>Ghi chú Masterdata</span><b>{r.masterdata_note||'-'}</b></div><div><span>Ghi chú Kế toán</span><b>{r.accounting_note||'-'}</b></div><div><span>Mã hàng mới</span><b>{r.result_material_code||'-'}</b></div></div></div><div className="request-card-side"><span className={`status ${r.status.toLowerCase()}`}>{labels[r.status]||r.status}</span><div className="actions">{actions(r)}</div></div></article>)}</div></section></>}
 {edit&&<div className="modal-backdrop"><div className="modal edit-modal"><button className="close" onClick={()=>setEdit(null)}>×</button><h2>Sửa toàn bộ yêu cầu</h2><p>{edit.request_no}</p><form className="edit-form" onSubmit={e=>saveEdit(e,false)}><label>Tên vật tư *<input required value={editForm.proposed_name} onChange={e=>setEditForm({...editForm,proposed_name:e.target.value})}/></label><label>Mã vật tư Nhà cung cấp<input value={editForm.supplier_material_code} onChange={e=>setEditForm({...editForm,supplier_material_code:e.target.value})}/></label><label>Mô tả / quy cách<textarea value={editForm.description} onChange={e=>setEditForm({...editForm,description:e.target.value})}/></label><div className="form-row"><label>Đơn vị tính<input value={editForm.unit} onChange={e=>setEditForm({...editForm,unit:e.target.value})}/></label><label>Nhóm vật tư<input value={editForm.material_group} onChange={e=>setEditForm({...editForm,material_group:e.target.value})}/></label></div><div className="modal-actions"><button className="secondary">Lưu thay đổi</button><button type="button" className="primary" onClick={e=>saveEdit(e as any,true)}>Lưu & gửi duyệt lại</button></div></form></div></div>}
 </main>}
createRoot(document.getElementById('root')!).render(<App/>);
